project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "functions/*.qmd"

website:
  navbar:
    logo: images/cccc_logo.png
    logo-alt: "Alt text"
    
    left:
      #- href: index.qmd
      #  text: cccc R Package
      - href: cccc-package.qmd
        text: cccc R Package
      - href: functions.qmd
        text: Functions
      - href: use-cases.qmd
        text: Use Cases
      - href: projects.qmd
        text: Projects
      - href: references.qmd
        text: References
      - href: about-us.qmd
        text: About Us
    right:
      - icon: github
        href: https://github.com/matildet/cccc
  page-footer:
    center: "© 2025 The cccc Team | Developed within the RIND Project"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-copy: true
    link-external-newwindow: true
    number-sections: false
